# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

# Don't run against PRs
pr: none

stages:
- stage: build
  jobs:
  - job: run_build
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script'

    - task: AzureCLI@1
      inputs:
        azureSubscription: 'Visual Studio Professional with MSDN (9330c17d-62d0-458a-b76d-2f7bd6f1f44e)'
        scriptLocation: 'scriptPath'
        scriptPath: 'https://raw.githubusercontent.com/jeremylindsayni/Simple-Azure-Web-App-Reference-Architecture/master/infrastructure/create-integration-resource-group.cmd'
        useGlobalConfig: true

    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
      displayName: 'Run a multi-line script'


- stage: deploy_to_integration
  dependsOn: build
  jobs:
  - job: run_tests
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
    - script: echo Test
