# Built-test-staging-prod pipeline

# Only run against master
trigger:
- master

# Don't run against PRs
pr: none

stages:
- stage: build
  jobs:
  - job: run_build
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
    - script: echo Build
    - task: AzureCLI@1
      displayName: 'Azure CLI $(System.DefaultWorkingDirectory)/Infrastructure Code/infrastructure/create-integration-resource-group.cmd'
      inputs:
        azureSubscription: 'Visual Studio Professional with MSDN (9330c17d-62d0-458a-b76d-2f7bd6f1f44e)'
        scriptPath: '$(System.DefaultWorkingDirectory)/Infrastructure Code/infrastructure/create-integration-resource-group.cmd'

- stage: test
  dependsOn: build
  jobs:
  - job: run_tests
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
    - script: echo Test
    
- stage: staging
  dependsOn: test
  jobs:
  - job: deploy_staging
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
    - script: echo Staging

- stage: prod
  dependsOn: staging
  jobs:
  - job: deploy_prod
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
    - script: echo Prod
